In [46]:
import yfinance as yf

tickers = ["AAPL", "JPM", "JNJ", "XOM", "PG", "NVDA", "SPY"]

data = yf.download(tickers, start = "2021-01-01")

data.head()

[*********************100%***********************]  7 of 7 completed

Price            Close                                                 \
Ticker            AAPL         JNJ         JPM       NVDA          PG
Date
2021-01-04  125.632507  133.628342  109.000519  13.060796  118.965546
2021-01-05  127.185799  135.199371  109.593620  13.350875  119.725166
2021-01-06  122.904518  136.471634  114.739708  12.563798  120.985420
2021-01-07  127.098427  136.932724  118.507622  13.290372  119.854652
2021-01-08  128.195435  136.650970  118.638481  13.223390  119.802856

Price                                    High                          ...  \
Ticker             SPY        XOM        AAPL         JNJ         JPM  ...
Date                                                                   ...
2021-01-04  342.436920  33.251331  129.709906  134.379738  110.723811  ...
2021-01-05  344.795380  34.853809  127.894501  135.557989  110.160560  ...
2021-01-06  346.856781  35.743179  127.224626  136.813171  115.803810  ...
2021-01-07  352.010254  36.023617  127.787708  137.496271  120.531163  ...
2021-01-08  354.015839  36.424221  128.758506  137.556068  118.926313  ...

Price             Open                            Volume                      \
Ticker              PG         SPY        XOM       AAPL       JNJ       JPM
Date
2021-01-04  120.553821  348.491002  33.211270  143301900  11765900  16819900
2021-01-05  119.112305  341.796208  33.523756   97664900   9602300  13731200
2021-01-06  119.785580  343.291184  35.582931  155088000   8230100  24909100
2021-01-07  120.631523  349.224628  36.055667  109578200   7747200  21940400
2021-01-08  119.526641  353.393703  36.215901  105158200   8228900  12035100

Price
Ticker           NVDA        PG        SPY       XOM
Date
2021-01-04  560640000   8330900  110210800  27764700
2021-01-05  322760000   6856400   66426200  44035100
2021-01-06  580424000  10578000  107997700  36484800
2021-01-07  461480000   7355400   68766800  29528100
2021-01-08  292528000   7448500   71677200  28628200

[5 rows x 35 columns]

In [47]:
close_prices = data["Close"]

close_prices.head()

Ticker,AAPL,JNJ,JPM,NVDA,PG,SPY,XOM
Date,,,,,,,
2021-01-04,125.632507,133.628342,109.000519,13.060796,118.965546,342.436920,33.251331
2021-01-05,127.185799,135.199371,109.593620,13.350875,119.725166,344.795380,34.853809
2021-01-06,122.904518,136.471634,114.739708,12.563798,120.985420,346.856781,35.743179
2021-01-07,127.098427,136.932724,118.507622,13.290372,119.854652,352.010254,36.023617
2021-01-08,128.195435,136.650970,118.638481,13.223390,119.802856,354.015839,36.424221

In [37]:
close_prices.to_csv('stock_prices.csv')

In [38]:
# DAILY RETURNS

import pandas as pd

close_prices = pd.read_csv('stock_prices.csv', index_col=0, parse_dates = True)


daily_returns = close_prices.pct_change().dropna()
daily_returns.head()

,AAPL,JNJ,JPM,NVDA,PG,SPY,XOM
Date,,,,,,,
2021-01-05,0.012364,0.011757,0.005441,0.022210,0.006385,0.006887,0.048193
2021-01-06,-0.033662,0.009410,0.046956,-0.058953,0.010526,0.005978,0.025517
2021-01-07,0.034123,0.003379,0.032839,0.057830,-0.009347,0.014858,0.007846
2021-01-08,0.008631,-0.002058,0.001104,-0.005040,-0.000432,0.005698,0.011121
2021-01-11,-0.023249,-0.004187,0.014924,0.025967,-0.006773,-0.006741,0.030356

In [61]:
# CUMULATIVE RETURNS (how much $1 invested in the beginning would be worth over time)

cumulative_returns = (1 + daily_returns).cumprod() - 1
cumulative_returns.tail()

,AAPL,JNJ,JPM,NVDA,PG,SPY,XOM
Date,,,,,,,
2026-08-12,1.405827,0.942550,2.350259,16.157452,0.211107,1.255860,3.773411
2026-08-13,1.429785,0.951635,2.331268,16.250096,0.212620,1.271600,3.739347
2026-08-14,1.435118,0.938752,2.328791,16.239377,0.215057,1.267103,3.783869
2026-08-17,1.432412,0.953795,2.311543,16.227892,0.203037,1.256386,3.855746
2026-08-18,1.467753,1.018879,2.332552,15.824395,0.205811,1.241142,3.979049

In [49]:
# VOLATILITY

rolling_volatility = daily_returns.rolling(window=30).std()
rolling_volatility.tail()

,AAPL,JNJ,JPM,NVDA,PG,SPY,XOM
Date,,,,,,,
2026-08-12,0.021913,0.015809,0.012727,0.025194,0.013616,0.007806,0.016925
2026-08-13,0.021772,0.015822,0.012438,0.024998,0.013578,0.007861,0.017008
2026-08-14,0.019890,0.014467,0.012453,0.024774,0.012569,0.007870,0.017025
2026-08-17,0.019735,0.014295,0.012349,0.024795,0.012452,0.007823,0.017004
2026-08-18,0.019891,0.014506,0.012365,0.025326,0.011614,0.007881,0.016295

In [50]:
# CORRELATION MATRIX (SPY excluded due to calculation amongst holdings, not benchmark)

holdings = ["AAPL", "JPM", "JNJ", "XOM", "PG", "NVDA"]
correlation_matrix = daily_returns[holdings].corr()
correlation_matrix

          AAPL       JPM       JNJ       XOM        PG      NVDA
AAPL  1.000000  0.327450  0.139756  0.150865  0.238556  0.483294
JPM   0.327450  1.000000  0.175269  0.307502  0.169573  0.302708
JNJ   0.139756  0.175269  1.000000  0.131425  0.446227 -0.107235
XOM   0.150865  0.307502  0.131425  1.000000  0.051311  0.057152
PG    0.238556  0.169573  0.446227  0.051311  1.000000 -0.011001
NVDA  0.483294  0.302708 -0.107235  0.057152 -0.011001  1.000000

In [59]:
# PORTFOLIO VS. BENCHMARK ($10k in holdings vs $10k in benchmark)

portfolio_cumulative = cumulative_returns[holdings].mean(axis=1)
benchmark_cumulative = cumulative_returns['SPY']

portfolio_value = 10000 * (1 + portfolio_cumulative)
benchmark_value = 10000 * (1 + benchmark_cumulative)


comparison = pd.DataFrame({
    'Portfolio ($10k Invested)' : portfolio_value,
    'S&P 500 ($10k Invested)' : benchmark_value
})
comparison.tail()

            Portfolio ($10k Invested)  S&P 500 ($10k Invested)
Date
2026-08-12               51401.008193             22558.602973
2026-08-13               51524.585864             22716.004625
2026-08-14               51568.276155             22671.033489
2026-08-17               51640.708401             22563.859201
2026-08-18               51380.733086             22411.423250

In [62]:
daily_returns.to_csv('daily_returns.csv')
cumulative_returns.to_csv('cumulative_returns.csv')
correlation_matrix.to_csv('correlation_matrix.csv')
comparison.to_csv('portfolio_vs_benchmark.csv')
rolling_volatility.to_csv('rolling_volatility.csv')

In [57]:
final_returns = cumulative_returns[holdings].iloc[-1].sort_values(ascending=False)
print((final_returns * 100).round(1).astype(str) + '%')

NVDA    1582.4%
XOM      397.9%
JPM      233.3%
AAPL     146.8%
JNJ      101.9%
PG        20.6%
Name: 2026-08-18 00:00:00, dtype: object

In [42]:
final_returns.to_csv('final_returns